name: Boost Scanners
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize

jobs:
  scanner:
    name: boost
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GoSec
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{ secrets.BOOST_API_DEV_TOKEN }}
          registry_module: boostsecurityio/gosec
          api_endpoint: https://api.dev.boostsec.io
