name: Boost SBOM Scanner
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize

jobs:
  scanner:
    name: boost
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute trivy-bom-dev
        if: github.event_name != 'pull_request'
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/trivy-sbom
          api_token: ${{ secrets.BOOST_API_DEV_TOKEN }}
          api_endpoint: https://api.dev.boostsec.io
      - name: Execute trivy-bom-prod
        if: github.event_name != 'pull_request'
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          registry_module: boostsecurityio/trivy-sbom
          api_token: ${{ secrets.BOOST_API_PROD_TOKEN }}
      - name: Semgrep with Node.JS
        uses: boostsecurityio/boostsec-scanner-github@v4
        env:
          SEMGREP_RULES: p/nodejs p/javascript p/typescript p/expressjs p/xss p/react
        with:
          api_token: ${{ secrets.BOOST_API_PROD_TOKEN }}
          registry_module: boostsecurityio/semgrep
      - name: Semgrep with Node.JS Dev
        uses: boostsecurityio/boostsec-scanner-github@v4
        env:
          SEMGREP_RULES: p/nodejs p/javascript p/typescript p/expressjs p/xss p/react
        with:
          api_token: ${{ secrets.BOOST_API_DEV_TOKEN }}
          registry_module: boostsecurityio/semgrep
          api_endpoint: https://api.dev.boostsec.io
